package com.bosch.ecommerce.price.controller;

import com.bosch.ecommerce.price.dto.CreatePriceRequest;
import com.bosch.ecommerce.price.dto.PriceHistoryResponse;
import com.bosch.ecommerce.price.dto.PriceResponse;
import com.bosch.ecommerce.price.service.PriceService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import java.net.URI;
import java.time.LocalDate;
import java.util.List;

@RestController
@RequestMapping("/api/v1/prices")
@Tag(name = "Prices", description = "Product prices, versions and price history")
public class PriceController {

    private final PriceService priceService;

    public PriceController(PriceService priceService) {
        this.priceService = priceService;
    }

    @Operation(summary = "Get the applicable price (today, or on a given date)")
    @GetMapping("/{productId}")
    public PriceResponse getPrice(
            @PathVariable("productId") String productId,
            @Parameter(description = "Optional effective date, format yyyy-MM-dd", example = "2026-10-03")
            @RequestParam(name = "date", required = false)
            @DateTimeFormat(iso = DateTimeFormat.ISO.DATE) LocalDate date) {
        return date == null ? priceService.getCurrentPrice(productId) : priceService.getPriceOn(productId, date);
    }

    @Operation(summary = "Get the full price history of a product (oldest version first)")
    @GetMapping("/{productId}/history")
    public List<PriceHistoryResponse> getHistory(@PathVariable("productId") String productId) {
        return priceService.getPriceHistory(productId);
    }

    @Operation(summary = "Create a new price version (version number is generated by the service)")
    @PostMapping
    public ResponseEntity<PriceResponse> createPrice(@Valid @RequestBody CreatePriceRequest request) {
        PriceResponse created = priceService.createPrice(request);
        URI location = URI.create("/api/v1/prices/" + created.productId());
        return ResponseEntity.status(HttpStatus.CREATED).location(location).body(created);
    }
}
