-- Price Service schema (owned exclusively by Price Service; managed by Flyway)
CREATE TABLE product_prices (
    price_id         BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 20001) PRIMARY KEY,
    product_id       VARCHAR(50)   NOT NULL,
    currency         VARCHAR(3)    NOT NULL,
    base_price       DECIMAL(12,2) NOT NULL,
    selling_price    DECIMAL(12,2) NOT NULL,
    discount_percent DECIMAL(5,2)  NOT NULL,
    valid_from       DATE          NOT NULL,
    valid_to         DATE,
    price_version    INT           NOT NULL,
    status           VARCHAR(20)   NOT NULL,
    created_at       TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_price_product_version UNIQUE (product_id, price_version),
    CONSTRAINT ck_price_base_nonneg     CHECK (base_price >= 0),
    CONSTRAINT ck_price_selling_nonneg  CHECK (selling_price >= 0),
    CONSTRAINT ck_price_discount_range  CHECK (discount_percent >= 0 AND discount_percent <= 100),
    CONSTRAINT ck_price_validity_window CHECK (valid_to IS NULL OR valid_to >= valid_from),
    CONSTRAINT ck_price_status          CHECK (status IN ('ACTIVE', 'SUPERSEDED'))
);

CREATE INDEX idx_price_product_validity ON product_prices (product_id, valid_from, valid_to);
