-- Tax Service schema (owned exclusively by Tax Service; managed by Flyway)
CREATE TABLE tax_rules (
    tax_rule_id      VARCHAR(40)  PRIMARY KEY,
    hsn_code         VARCHAR(10)  NOT NULL,
    hsn_level        VARCHAR(10)  NOT NULL DEFAULT 'HEADING',
    hsn_description  VARCHAR(255),
    cgst_rate        DECIMAL(5,2),
    sgst_rate        DECIMAL(5,2),
    igst_rate        DECIMAL(5,2),
    cess_rate        DECIMAL(5,2),
    effective_from   DATE         NOT NULL,
    effective_to     DATE,
    status           VARCHAR(40)  NOT NULL,
    source_reference VARCHAR(255),
    created_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_tax_rule_hsn_from   UNIQUE (hsn_code, effective_from),
    CONSTRAINT ck_tax_rule_window     CHECK (effective_to IS NULL OR effective_to >= effective_from),
    CONSTRAINT ck_tax_rule_cgst       CHECK (cgst_rate IS NULL OR (cgst_rate >= 0 AND cgst_rate <= 100)),
    CONSTRAINT ck_tax_rule_sgst       CHECK (sgst_rate IS NULL OR (sgst_rate >= 0 AND sgst_rate <= 100)),
    CONSTRAINT ck_tax_rule_igst       CHECK (igst_rate IS NULL OR (igst_rate >= 0 AND igst_rate <= 100)),
    CONSTRAINT ck_tax_rule_cess       CHECK (cess_rate IS NULL OR (cess_rate >= 0 AND cess_rate <= 100))
);

CREATE INDEX idx_tax_rules_hsn_window ON tax_rules (hsn_code, effective_from, effective_to);

-- Product -> HSN classification. product_id is an opaque identifier owned by the catalogue;
-- Tax Service stores only the reference, never the product master data or prices.
-- hsn_code is a LOGICAL reference to tax_rules.hsn_code (not a foreign key, because one HSN can
-- have several effective-dated rules, so hsn_code alone is not unique in tax_rules).
CREATE TABLE product_tax_mapping (
    mapping_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id          VARCHAR(50)  NOT NULL,
    hsn_code            VARCHAR(10)  NOT NULL,
    hsn_level           VARCHAR(10)  NOT NULL DEFAULT 'HEADING',
    hsn_description     VARCHAR(255),
    verification_status VARCHAR(120),
    tax_source          VARCHAR(255),
    effective_from      DATE         NOT NULL,
    effective_to        DATE,
    status              VARCHAR(20)  NOT NULL,
    created_at          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_mapping_product_from UNIQUE (product_id, effective_from),
    CONSTRAINT ck_mapping_window       CHECK (effective_to IS NULL OR effective_to >= effective_from),
    CONSTRAINT ck_mapping_status       CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE INDEX idx_mapping_product_window ON product_tax_mapping (product_id, effective_from, effective_to);
